name: Deploy to Dev Environment

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ["backend-dev"]

    steps:
      - uses: actions/checkout@v3
      - name: "Add environment files"
        run: echo "${{ secrets.DEV_ENV }}"  | base64 -d > ./backend/.env
      - name: Run docker compose
        run: docker compose -f backend/deployment/dev-deployment.yml up -d --build --force-recreate backend
